
pipeline {
    agent any
    // environment:
    //   TAG:"${env.BUILD_NUMBER}"
    stages {
        stage ('install dependencies') {
            steps {
                dir('my-cicd-project-day2') {
                 sh 'python3 -m venv .venv'
                 sh '.venv/bin/python -m pip install -r requirements.txt'
                }
            }
        }
        stage ('test') {
            steps {
                dir('my-cicd-project-day2') {
                   sh '.venv/bin/python -m pytest'
                }
            }
        }
        stage ('build') {
            steps {
                dir('my-cicd-project-day2') {
                   sh 'docker build -t my-flask-app:${BUILD_NUMBER} .'
                }
            } 
        }
        stage ('run container') {
            steps {
                sh 'docker rm -f cicd-day2-cont || true'
                sh 'docker run -d --name cicd-day2-cont -p 5000:5000 my-flask-app:${BUILD_NUMBER}'
            }
        }
        stage ('test container') {
            steps {
                sh 'sleep 5'
                sh 'curl http://localhost:5000'
                sh 'curl http://localhost:5000/health'
            }
        }

    }
    post {
        success {
            echo 'CI/CD Pipeline completed successfully!'
            echo 'Python tests passed.'
            echo 'Docker image built successfully.'
            echo 'Container health check passed.'
        }
        failure {
            echo 'CI/CD Pipeline failed!'
            echo 'Please check the failed stage.'
        }
    }
}
