pipeline {
    agent any

    stages {

        stage('Check Workspace') {
            steps {
                sh 'pwd'
                sh 'ls -la'
                sh 'ls -la my-cicd-project-day1'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('my-cicd-project-day1') {
                    sh 'python3 -m venv .venv'
                    sh '.venv/bin/python -m pip install -r requirements.txt'
                }
            }
        }

        stage('Test') {
            steps {
                dir('my-cicd-project-day1') {
                    sh '.venv/bin/python -m pytest'
                }
            }
        }
    }

    post {
        success {
            echo 'CI Pipeline completed successfully!'
        }

        failure {
            echo 'CI Pipeline failed!'
        }
    }
}
